PPW1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic.base import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='story1/')),
    path('story1/', include(('story1.urls', 'story1'), namespace='story1')),
    path('story4/', include(('story4.urls', 'story4'), namespace='story4')),
]

story1/urls.py
#STORY1 - APP URLS#
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import index

urlpatterns = [
	path('', index, name='story1_index'),
]

story4/urls.py
#STORY1 - APP URLS#
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from .views import index, clear_sched, create_sched

urlpatterns = [
	path('', index, name='story4_index'),
	path('story5-clr-event/', clear_sched, name='clr_event'),
	path('story5-crt-event/', create_sched, name='crt_event'),
]

story1/models.py
from django.db import models

# Create your models here.

story4/models.py
from django.db import models

class JadwalPribadi(models.Model):
	date = models.DateField()
	time = models.TimeField()
	event_name = models.CharField(max_length=32, blank=False)
	location = models.CharField(max_length=48)
	category = models.CharField(max_length=16)



# Create your models here.

story4/forms.py
from .models import JadwalPribadi
from django import forms

fieldStyling = (
	'margin-left: auto;'
	+'margin-right: auto;'
	+'margin-top: 10px;'
	+'margin-bottom: 10px;'
	+'padding-left: 25px;'
	+'padding-right: 25px;'
	+'padding-top: 5px;'
	+'padding-top: 5px;'
	+'min-width: 260px;'
	+'justify-content: center;'
)

class JadwalForm(forms.Form):
	date = forms.DateField(label='',
		required=True, 
		#input_formats=settings.DATE_INPUT_FORMATS,
		widget=forms.DateInput(
			attrs={
			'class' : 'input-group-text',
			'id' : 'f_date',
			'type':'date',
			'style' : fieldStyling,
			}
		)
	)
	time = forms.TimeField(label='',
		required=True,
		widget=forms.TimeInput(attrs={'class' : 'input-group-text','id' : 'f_time', 'type' : 'time', 'style':fieldStyling}))
	eventName = forms.CharField(label='',
		required=True,
		max_length=32,
		widget=forms.TextInput(attrs={'class' : 'form-control','id' : 'str_name', 'type':'text','placeholder':'Nama kegiatan', 'style':fieldStyling}))
	location = forms.CharField(label='',
		max_length=48,
		required=False,
		widget=forms.TextInput(attrs={'class' : 'form-control','id' : 'str_loc', 'type':'text','placeholder':'Tempat', 'style':fieldStyling}))
	category = forms.CharField(label='',
		max_length=16,
		required=False,
		widget=forms.TextInput(attrs={'class' : 'form-control','id' : 'str_ctg', 'type':'text','placeholder':'Kategori', 'style':fieldStyling}))

story1/views.py
from django.shortcuts import render

response = {}

def index(request):
	return render(request, 'index.html', response)

# Create your views here.

story4/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import JadwalPribadi
from .forms import JadwalForm

response = {}
# def index(request):
# 	return render(request, 'index4.html', response)

def index(request):
	response['schedules'] = JadwalPribadi.objects.all()
	return render(request, 'index4.html', response)

def clear_sched(request):
	JadwalPribadi.objects.all().delete()
	return HttpResponseRedirect('/story4')

def create_sched(request):
	form = JadwalForm(request.POST or None)
	if (request.method == 'POST' and form.is_valid()):
		response['date'] = request.POST.get('date')	
		response['time'] = request.POST.get('time')
		response['event_name'] = request.POST.get('event_name')
		response['location'] = request.POST.get('location')
		response['category'] = request.POST.get('category')


		Jadwal_submit = JadwalPribadi(
			date=response['date'],
			time=response['time'],
			event_name=response['event_name'],
			location=response['location'], 
			category=response['category'],
		)

		Jadwal_submit.save()
		return HttpResponseRedirect('/story4')
	else :
		response['form_sched'] = JadwalForm()
	return render(request, 'sched.html', response)

story1/templates/footer.html
{% load static %}

{% block content %}

	<!-- jQuery, Popper.js, Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	</body>

</html>

{% endblock %}

story1/templates/header.html
{% load static %}
{% block header %}
<!DOCTYPE html>

<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>STORYPPW-jagonyappw</title>

    <!-- Bootstrap's CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <!-- Custom (static) CSS -->
    <link href=" {% static '/css/style.css' %}" rel="stylesheet" id="custom-css-file">

    <!-- Custom fonts -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,400i,700,900" rel="stylesheet">
  </head>
{% endblock %}
{% include "navbar.html" %}

story1/templates/index.html
{% include "header.html" %}
{% block index_1 %}
    <div class="imgbox">
        <img class="center-fit" src='https://i.imgur.com/XryV3yW.jpg' alt="DoubleExp-Photography">
    </div>
    <section>
        <style>
            h1 {
                color: #2f2c2c;
                font: 48px "Source Sans Pro", arial, sans-serif;
                font-weight: 700
            }

            p {
                color: #434141;
                font: 18px "Varela Round", sans-serif;
                font-weight: 50;
            }

            * {
                margin: 0;
                padding: 0;
            }

            .imgbox {
                display: grid;
                height: 100%;
            }

            .center-fit {
                max-width: 100%;
                max-height: 100vh;
                margin: auto;
            }

            .center-Text {
                max-width: 50%;
                min-width: 640px;
                max-height: 40%;
                min-height: 100px;
            }
        </style>

        <h1 class="center-Text">
            Tentang Saya...
        </h1>

        <p class="center-Text">
            <b>Nama</b>             : Adam Maulana<br />
            <b>NPM</b>              : 1706043651<br />
            <b>Perguruan Tinggi</b> : Universitas Indonesia<br />
            <b>Fakultas</b>         : Ilmu Komputer<br />
            <b>Hobi</b>             : Baca buku dan main/mendengarkan musik<br />
        <p>
            <br />
            <b>Deskripsi diri</b>   :
        </p>
        </p>
        <p>
            Saya Adam Maulana, merupakan anak terakhir dari empat bersaudara yang bertempat tinggal di ujung Utara Kota Jakarta. Saya mengenal diri saya sendiri sebagai orang yang cukup semangat
            untuk melakukan perbaikan secara bertahap, baik terhadap diri sendiri maupun orang lain. Di kampus yang saya cintai ini, saya memilih untuk aktif di beberapa Kepanitiaan dan Lembaga Dakwah Fakultas,
            tujuannya adalah untuk berkontribusi untuk meyebarkan kebaikan, serta melatih kemampuan diri baik <i>soft-skill</i> maupun <i>hard-skill</i>.
            <br />
            <br />
        </p>

    </section>

    <div class="imgbox">
        <img class="center-fit" src='http://www.about.tarung2017.com/foto/224.jpg' ">
    </div>
    <section>
        <style>
            h1 {
                color: #2f2c2c;
                font: 48px "Source Sans Pro", arial, sans-serif;
                font-weight: 700
            }

            p {
                color: #434141;
                font: 18px "Varela Round", sans-serif;
                font-weight: 50;
            }

            * {
                margin: 0;
                padding: 0;
            }

            .imgbox {
                display: grid;
                height: 100%;
            }

            .center-fit {
                max-width: 100%;
                max-height: 100vh;
                margin: auto;
            }

            .center-Text {
                max-width: 50%;
                min-width: 640px;
                max-height: 40%;
                min-height: 100px;
            }
        </style>

        <h1 class="center-Text">
            Tentang Saya...
        </h1>

        <p class="center-Text">
            <b>Nama</b>             : M. Nadhirsyah Indra<br />
            <b>NPM</b>              : 1706039383<br />
            <b>Perguruan Tinggi</b> : Universitas Indonesia<br />
            <b>Fakultas</b>         : Ilmu Komputer<br />
            <b>Hobi</b>             : Main Game<br />
        <p>
            <br />
            <b>Deskripsi diri</b>   :
        </p>
        </p>
        <p>
            Teman saya ini sering dipanggil "Nadhir", ia merupakan sosok yang cukup meyenangkan orang lain, ia juga sangat mudah untuk diajak main kesana dan kemari. Ia pun memiliki banyak teman di kampusnya.
            <br />
            <br />
        </p>

    </section>

    </section>

    <div class="imgbox">
        <img class="center-fit" src='http://www.about.tarung2017.com/foto/119.jpg' ">
    </div>
    <section>
        <style>
            h1 {
                color: #2f2c2c;
                font: 48px "Source Sans Pro", arial, sans-serif;
                font-weight: 700
            }

            p {
                color: #434141;
                font: 18px "Varela Round", sans-serif;
                font-weight: 50;
            }

            * {
                margin: 0;
                padding: 0;
            }

            .imgbox {
                display: grid;
                height: 100%;
            }

            .center-fit {
                max-width: 100%;
                max-height: 100vh;
                margin: auto;
            }

            .center-Text {
                max-width: 50%;
                min-width: 640px;
                max-height: 40%;
                min-height: 100px;
            }
        </style>

        <h1 class="center-Text">
            Tentang Saya...
        </h1>

        <p class="center-Text">
            <b>Nama</b>             : Moh. Adli Daffa W.<br />
            <b>NPM</b>              : 1706984663<br />
            <b>Perguruan Tinggi</b> : Universitas Indonesia<br />
            <b>Fakultas</b>         : Ilmu Komputer<br />
            <b>Hobi</b>             : Belajar dan ngoding<br />
<p>
            <br />
            <b>Deskripsi diri</b>   :
        </p>
        </p>
        <p>
            Teman saya yang ini sering dipanggil Adli oleh kerabat-kerabatnya. Ia merupakan teman saya yang sangat perhatian dengan dunia akademis dan menggali ilmu-ilmu yang
            ada di Fasilkom. Kesehariannya ia selalu mencoba dan belajar hal-hal seputar pemrograman agar masa depannya ia dapat menjadi seorang <i>expert</i> di bidang teknologi dan informasi, khususnya pemrograman komputer.
            <br />
            <br />
        </p>

    </section>
</body>

{% endblock %}

{% include "footer.html" %}

story1/templates/index4.html
{% include "header.html" %}
{% block index4 %}
<body id="page-top">
    <div class="page-1-1" id="page1">
        <div class="container-fluid">
            <div class="row-sm">
                <div class="col-sm"></div>
                <div class="col-sm">

                    <div class="row justify-content-md-center"
                        style="
                        max-width: 600px;
                        margin-left: auto;
                        margin-right: auto;
                        margin-top: 100px;
                        margin-bottom: 50px;">
                        <img src='https://i.imgur.com/XryV3yW.jpg' alt="DoubleExp-Photography" class="rounded mx-auto d-block" alt="wkwkwk" style="
                        margin: auto;
                        width: 24vw; height: 18vw;">
                        
                    
                    </div>


                    <div class="row justify-content-md-center"
                        style="
                        max-width: 600px;
                        margin-left: auto;
                        margin-right: auto;
                        margin-top: 50px;
                        margin-bottom: 50px;">
                        <div class="input-group mb-3"
                            style="
                            
                            margin-left: auto;
                            margin-right: auto;
                            margin-top: 25px;
                            margin-bottom: 25px;
                            border-left-width: 2.5rem;
                            border-right-width: 2.5rem;
                            padding-left: 25px;
                            padding-right: 25px;
                            padding-top: 5px;
                            padding-top: 5px;
                            ">
                            <input type="text" class="form-control" placeholder="What's Up?" aria-label="What's Up?" aria-describedby="button-addon2">
                            <div class="input-group-append">
                                <button class="btn btn-outline-secondary" type="button" id="button-addon2">Post!</button>
                          </div>
                        </div>

                        <form action="{% url 'story4:clr_event' %}" method="GET">
                    <a href="story5-clr-event" class="btn btn-primary btn-lg" role="button" aria-disabled="false">Clear Event!</a>
                    
                    </div>
                    {% for data in schedules%}
                    <!-- ===============individual schedule view start -->
                    <div class="row justify-content-md-center"
                        style="
                        max-width: 600px;
                        margin-left: auto;
                        margin-right: auto;
                        margin-top: 50px;
                        margin-bottom: 50px;">
                        <div class="alert alert-info" role="alert">
                            <div class="row">
                                <span class="badge badge-dark">
                                    <a><Strong>{{ data.date | date:'l'}}</Strong></a><br/>
                                    <a class="big-text1xx">{{ data.date | date:'d'}}</a><br/>
                                    <a><strong>{{ data.date | date:'M Y'}}</strong></a>
                                </span>
                                <span class="badge badge-info">
                                    <a class="desc-textxx">{{ data.event_name }}</a><br/><br/>
                                    <a class="desc-textxx-small">Location : {{ data.location }}</a><br/>
                                    <a class="desc-textxx-small">Category : {{ data.category }}</a><br/>
                                    <a class="desc-textxx-small">Time : {{ data.time | time:'h:i A'}}</a>
                                </span>
                            </div>
                        </div>
                       <!-- ==========individual schedule view end here -->
                    </div>
                    {% endfor %}
            
                </div>
                <div class="col-sm"></div>
            </div>
        </div>  
            
    </div>
</body>
{% endblock %}
{% include "footer.html" %}

story1/templates/navbar.html
{% block navbar %}

<body id="page-top">

	<!-- Navigation Start Here -->
	<div class="pos-f-t">
    <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4" id = "navbar_dark">
            <a class="text-navbar-1" href="/story1">Story1</a> <br/>
            <a class="text-navbar-1" href="/story4">Story4</a> <br/>
            <a class="text-navbar-1" href="/story4/story5-crt-event">Create Schedule!</a> <br/>
            

        </div>
    </div>
    	<nav class="navbar navbar-dark bg-dark">
        	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation" id="nav_button">
            <span class="navbar-toggler-icon"></span>
        	</button>
        </nav>
	</div>

	<!-- Navigation End Here -->
{% endblock %}

story1/templates/sched.html
{% include "header.html" %}


{% block sched %}
<form id="form" method="POST" action="{% url 'story4:crt_event' %}">
 	{% csrf_token %}

	{{ form_sched.as_p }}

	<input type='submit' value='Create!' class="btn btn-primary btn-lg"/>
</form>


{% endblock %}

{% include "footer.html" %}